# Generated by Django 5.0.1 on 2024-01-08 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user12_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User12',
            new_name='User',
        ),
    ]
